// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDOlGfUK-ze_lh-lYEZ9Qy5QXVl8M3Yg',
    appId: '1:767568798856:android:e19426cb04157b2e90ab3d',
    messagingSenderId: '767568798856',
    projectId: 'flutter-training-a2482',
    databaseURL: 'https://flutter-training-a2482-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-a2482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSJYvy3B1aNEauOcvabqfKr0WLgLJBqU',
    appId: '1:767568798856:ios:d34ac8f6c8e7cb9e90ab3d',
    messagingSenderId: '767568798856',
    projectId: 'flutter-training-a2482',
    databaseURL: 'https://flutter-training-a2482-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-training-a2482.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );
}
